# Generated by Django 3.0.5 on 2020-05-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('total_time', models.TimeField()),
                ('average', models.TimeField()),
                ('hints', models.PositiveIntegerField()),
                ('wrong_sets', models.PositiveIntegerField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
