# Generated by Django 3.0.5 on 2020-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200516_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='total_time',
            field=models.FloatField(),
        ),
    ]
