# Generated by Django 3.0.5 on 2020-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200516_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
